limit:
  minimum: 3
  maximum: 1000


spring:
  application:
#    Matchs limit-service.yml file in local-git-repo
    name: limit-service
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: qa
  cloud:
    config:
      profile: qa